---
title: "Tablas de los participantes del estudio de Mpox"
author: "Proyecto Mpox"
date: '`r Sys.Date()`'
output:
  word_document:
    number_sections: yes
    toc: yes
  html_document:
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(dplyr)
library(modeest)
library(ggplot2)
library(ggThemeAssist)
library(tidyr)
library(lubridate)
library(openxlsx)
library(readxl)
library(boot)
library(stringr)
#devtools::install_github("kupietz/kableExtra")
library(printr)
library(rstatix)
```

```{r,include=FALSE}
##### -------------- 0. Cargar base de los vacunados ------------

vacuna<-read.csv("02. CRF Vacunacion/2CRFVacunacin_DATA_2025-04-23_1458.csv",header = T, encoding = "Latin1")

# - Quitar espacios en blanco sobrantes de la variable codigo_participante de la base de los vacunados:

vacuna <- vacuna %>%
  mutate(codigo_participante = gsub("\\s+", "", codigo_participante))%>%
  mutate(codigo_participante=str_trim(codigo_participante))

```


```{r, include=FALSE}
##### -------------- 1. Editar tabla de ECA ------------

#Cargar el data frame:

datos_eca<-read.csv("01. CRF Datos y criterios/1CRFDatosYCriteriosR_DATA_2025-04-23_1456.csv",header = T, encoding = "Latin1")

# Quitar los NA de los ID

datos_eca<-datos_eca[!is.na(datos_eca$numero_documento),]

```

```{r,include=FALSE}
#### -------------- 1.1. Editar de la tabla de ECA el código del participante ------------

# Crear la variable del codigo participante, uniendo las variables codigo8 y record_id
datos_eca$codigo_participante<-paste0(datos_eca$codigo8,
                                          "-",datos_eca$record_id)

# - Quitar espacios en blanco sobrantes

datos_eca<-datos_eca%>%
  mutate(codigo_participante = gsub("\\s+", "", codigo_participante))%>%
  mutate(codigo_participante=str_trim(codigo_participante))

# - Eliminar el participante COL-CUC-243 (solicitud por falla de selección)

datos_eca <- datos_eca %>%
  filter(codigo_participante != "COL-CUC-243")
```



```{r,include=FALSE}
#### -------------- 1.2. Codificar las variables solicitadas ------------


# -- SOCIODEMOGRÁFICAS --

# ---- Edad

datos_eca$fecha_consentimiento<-as.Date(datos_eca$fecha_consentimiento);class(datos_eca$fecha_consentimiento)
datos_eca$fecha_nacimiento<-as.Date(datos_eca$fecha_nacimiento);class(datos_eca$fecha_nacimiento)


datos_eca$edad<-round(time_length(difftime(datos_eca$fecha_consentimiento,
                                           datos_eca$fecha_nacimiento),"year"),0)

summary(datos_eca$edad)



# ---- Sexo asignado al nacer

datos_eca$sexo[datos_eca$sexo == 1]<-"Femenino"
datos_eca$sexo[datos_eca$sexo == 2]<-"Masculino"
datos_eca$sexo[datos_eca$sexo == 3]<-"Intersexual"


# ---- Genero (clasificación de RedCap)

datos_eca$genero[datos_eca$genero == 1]<-"Hombre"
datos_eca$genero[datos_eca$genero == 2]<-"Mujer"
datos_eca$genero[datos_eca$genero == 3]<-"No binario"
datos_eca$genero[datos_eca$genero == 4]<-"Otro"


# ---- Identidad de Genero

datos_eca$genero2[datos_eca$sexo == "Femenino" & datos_eca$genero == "Mujer"]<-"Mujer cisgenero"
datos_eca$genero2[datos_eca$sexo == "Masculino" & datos_eca$genero == "Hombre"]<-"Hombre cisgenero"

#View(datos_eca[,c("sexo","genero","genero2")])

datos_eca$genero2[datos_eca$sexo == "Femenino" & datos_eca$genero == "Hombre"]<-"Hombre transgenero"
datos_eca$genero2[datos_eca$sexo == "Masculino" & datos_eca$genero == "Mujer"]<-"Mujer transgenero"

datos_eca$genero2[datos_eca$sexo == "Femenino" & datos_eca$genero %in% c("No binario","Otro")]<-"Indefinido"
datos_eca$genero2[datos_eca$sexo == "Masculino" & datos_eca$genero %in% c("No binario","Otro")]<-"Indefinido"


# ---- Codificar grupos de VIH/PrEP/Factor de riesgo

datos_eca$participante_convive_virus<-ifelse(datos_eca$participante_convive_virus == 1, "Si","No")

datos_eca$participante_prep[datos_eca$participante_prep == 1]<-"Si"
datos_eca$participante_prep[datos_eca$participante_prep == 2]<-"No"

datos_eca$factor_riesgo<-ifelse(datos_eca$factor_riesgo == 1, "Si","No")

#View(datos_eca[,c("participante_convive_virus","participante_prep","factor_riesgo")])


# - otra variable

datos_eca$confirmacion_entidad[datos_eca$participante_convive_virus == "Si"]<-"VIH"

datos_eca$confirmacion_entidad[is.na(datos_eca$confirmacion_entidad) & datos_eca$participante_convive_virus == "No" &
                             datos_eca$participante_prep == "Si" & datos_eca$factor_riesgo == "No"]<-"Prep"

datos_eca$confirmacion_entidad[is.na(datos_eca$confirmacion_entidad) & datos_eca$participante_convive_virus == "No" &
                             datos_eca$participante_prep == "No" & datos_eca$factor_riesgo == "Si"]<-"Factor de riesgo"


# ---- Vive con VIH

datos_eca$vih<-ifelse(datos_eca$confirmacion_entidad == "VIH","Si","No")


# ---- Recuento CD4 (cél/µL)

# Adjuntar conteos de CD4
conteo_cd4 <- read_excel("20250520_Conteo_CD4.xlsx")

conteo_cd4<-conteo_cd4%>%
  mutate(codigo_participante = gsub("\\s+", "", codigo_participante))%>%
  mutate(codigo_participante=str_trim(codigo_participante))

# Contar cantidad de pacientes:

length(unique(conteo_cd4$codigo_participante))


# Adjuntar los cd4 a la base de ECA:

datos_eca<-datos_eca %>%
  left_join(conteo_cd4,by=c("codigo_participante"))


#nvac<-datos_vacunados%>%group_by(codigo_participante)%>%summarise(n())
summary(datos_eca$cd4)

datos_eca$categorias_cd4<-NA

datos_eca$categorias_cd4[datos_eca$cd4 >= 200 & datos_eca$cd4 <= 349]<-"VIH 200-349"
datos_eca$categorias_cd4[datos_eca$cd4 >= 350 & datos_eca$cd4 <= 499]<-"VIH 350-499"
datos_eca$categorias_cd4[datos_eca$cd4 >= 500 & datos_eca$cd4 <= 749]<-"VIH 500-749"
datos_eca$categorias_cd4[datos_eca$cd4 >= 750 & datos_eca$cd4 <= 999]<-"VIH 750-999"
datos_eca$categorias_cd4[datos_eca$cd4 >= 1000]<-"VIH mayor 1000"


datos_eca$confirmacion_entidad<-as.character(datos_eca$confirmacion_entidad)


#View(datos_eca[,c("codigo_participante","confirmacion_entidad","categorias_cd4")])

datos_eca$categorias_cd4[datos_eca$confirmacion_entidad == "Prep" & datos_eca$categorias_cd4 %in% c("VIH 200-349","VIH 350-499","VIH 500-749","VIH 750-999","VIH mayor 1000")]<-NA



# ---- Usuario de PrEP

datos_eca$prep<-ifelse(datos_eca$confirmacion_entidad == "Prep","Si","No")



# ----- Conductas sexules de riesgo

# ---- Hombre que practica sexo con hombres (sólo para los que no son usuarios del PrEP)

datos_eca$hombre_practica_sexo[datos_eca$hombre_practica_sexo == 1]<-"Si"
datos_eca$hombre_practica_sexo[datos_eca$hombre_practica_sexo == 2]<-"No"


# ---- Sexo transaccional

datos_eca$participante_sexo_transaccional[datos_eca$participante_sexo_transaccional == 1]<-"Si"
datos_eca$participante_sexo_transaccional[datos_eca$participante_sexo_transaccional == 2]<-"No"


# ---- Múltiples parejas sexuales

datos_eca$participante_mult_parejas[datos_eca$participante_mult_parejas == 1]<-"Si"
datos_eca$participante_mult_parejas[datos_eca$participante_mult_parejas == 2]<-"No"


#View(datos_eca[,c("confirmacion_entidad",
#                  "hombre_practica_sexo","participante_sexo_transaccional","participante_mult_parejas")])


# ---- Afiliación al sistema de salud

datos_eca$afiliciacion_seguridad_social[datos_eca$afiliciacion_seguridad_social == 1]<-"Contributivo"
datos_eca$afiliciacion_seguridad_social[datos_eca$afiliciacion_seguridad_social == 2]<-"Subsidiado"
datos_eca$afiliciacion_seguridad_social[datos_eca$afiliciacion_seguridad_social == 3]<-"Especial"
datos_eca$afiliciacion_seguridad_social[datos_eca$afiliciacion_seguridad_social == 4]<-"Otro"
datos_eca$afiliciacion_seguridad_social[datos_eca$afiliciacion_seguridad_social == 5]<-"Ninguno"



# ---- Escolaridad

datos_eca$escolaridad2[datos_eca$escolaridad %in% c(1:3)]<-"Baja"
datos_eca$escolaridad2[datos_eca$escolaridad %in% c(4:7)]<-"Media"
datos_eca$escolaridad2[datos_eca$escolaridad %in% c(8:11)]<-"Alta"

table(datos_eca$escolaridad2)


# ---- Número de personas con quienes vive

datos_eca$numero_personas_convive <- ifelse(datos_eca$numero_personas_convive_2 == 0,"Ninguna",
                                            ifelse(datos_eca$numero_personas_convive_2 == 1,"Con 1 persona",
                                                   ifelse(datos_eca$numero_personas_convive_2 %in% c(2,3),"Con 2 o 3 personas",
                                                          "Con 4 personas o más")))


#View(datos_eca[,c("numero_personas_convive_2","numero_personas_convive")])


```

```{r,include=FALSE}
sum(is.na(datos_eca$asignacion)) #0
table(datos_eca$asignacion)
```

```{r,include=FALSE}
# Filtrar a los vacunados

datos_eca <- datos_eca %>%
  filter(codigo_participante %in% c(vacuna$codigo_participante))

```


```{r,include=FALSE}
#Dividir bases entre tardío y temprano, teniendo en cuenta la base del ECA
temprano<-datos_eca[datos_eca$asignacion == 2,]
tardio<-datos_eca[datos_eca$asignacion == 1,]
```



<div style="text-align:center;">
**Tabla 1. Características sociodemográficas de los pacientes con asignación del ECA**
</div>


```{r, include=FALSE}
# Temprana

# --- Edad

shapiro.test(temprano$edad)


edad_temp<-data.frame(Variables="Mediana (RIC)",
                 Total = paste(prettyNum(round(summary(temprano$edad)[3],2),big.mark = ".",decimal.mark = ","),
                               paste0("(",
                               prettyNum(round(summary(temprano$edad)[2],2),big.mark = ".",decimal.mark = ",")),
                               "-",
                        paste0(prettyNum(round(summary(temprano$edad)[5],2),big.mark = ".",decimal.mark = ","),
                                      ")")))

names(edad_temp)<-c("Variables", "Temprana")


# --- Sexo asignado al nacer

(sex_temp<-table(temprano$sexo))

(prop_sex_temp<-round(prop.table(sex_temp),4))

sex_temp<-as.data.frame(sex_temp)
prop_sex_temp<-as.data.frame(prop_sex_temp)

sex_temp<-merge(sex_temp,prop_sex_temp,by=c("Var1"))

sex_temp$etiqueta<-paste(prettyNum(sex_temp$Freq.x,big.mark = ".",decimal.mark = ","),
                    paste0("(",prettyNum(sex_temp$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

sex_temp<-sex_temp[,c(1,4)]

sex_temp$Var1<-as.character(sex_temp$Var1)

names(sex_temp)<-c("Variables", "Temprana")


# --- Identidad de genero

(genero2_temp<-table(temprano$genero2))

(prop_genero2_temp<-round(prop.table(genero2_temp),4))

genero2_temp<-as.data.frame(genero2_temp)
prop_genero2_temp<-as.data.frame(prop_genero2_temp)

genero2_temp<-merge(genero2_temp,prop_genero2_temp,by=c("Var1"))

genero2_temp$etiqueta<-paste(prettyNum(genero2_temp$Freq.x,big.mark = ".",decimal.mark = ","),
                paste0("(",prettyNum(genero2_temp$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

genero2_temp<-genero2_temp[,c(1,4)]

genero2_temp$Var1<-as.character(genero2_temp$Var1)

names(genero2_temp)<-c("Variables", "Temprana")


# --- Vive con VIH

(vih_temp<-table(temprano$vih))

(prop_vih_temp<-round(prop.table(vih_temp),4))

vih_temp<-as.data.frame(vih_temp)
prop_vih_temp<-as.data.frame(prop_vih_temp)

vih_temp<-merge(vih_temp,prop_vih_temp,by=c("Var1"))

vih_temp$etiqueta<-paste(prettyNum(vih_temp$Freq.x,big.mark = ".",decimal.mark = ","),
                paste0("(",prettyNum(vih_temp$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

vih_temp<-vih_temp[,c(1,4)]

vih_temp$Var1<-as.character(vih_temp$Var1)

names(vih_temp)<-c("Variables", "Temprana")



# --- Recuento CD4 (cél/µL)

shapiro.test(temprano$cd4)

cd4_temp<-data.frame(Variables="Mediana (RIC)",
                 Total = paste(prettyNum(round(summary(temprano$cd4)[3],2),big.mark = ".",decimal.mark = ","),
                               paste0("(",
                               prettyNum(round(summary(temprano$cd4)[2],2),big.mark = ".",decimal.mark = ",")),
                               "-",
                        paste0(prettyNum(round(summary(temprano$cd4)[5],2),big.mark = ".",decimal.mark = ","),
                                      ")")))

names(cd4_temp)<-c("Variables", "Temprana")



# --- Categorías de CD4

(cat_cd4_temp<-table(temprano$categorias_cd4))

(prop_cat_cd4_temp<-round(prop.table(cat_cd4_temp),4))

cat_cd4_temp<-as.data.frame(cat_cd4_temp)
prop_cat_cd4_temp<-as.data.frame(prop_cat_cd4_temp)

cat_cd4_temp<-merge(cat_cd4_temp,prop_cat_cd4_temp,by=c("Var1"))

cat_cd4_temp$etiqueta<-paste(prettyNum(cat_cd4_temp$Freq.x,big.mark = ".",decimal.mark = ","),
              paste0("(",prettyNum(cat_cd4_temp$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

cat_cd4_temp<-cat_cd4_temp[,c(1,4)]

cat_cd4_temp$Var1<-as.character(cat_cd4_temp$Var1)

names(cat_cd4_temp)<-c("Variables", "Temprana")



# --- Prep

(prep_temp<-table(temprano$prep))

(prop_prep_temp<-round(prop.table(prep_temp),4))

prep_temp<-as.data.frame(prep_temp)
prop_prep_temp<-as.data.frame(prop_prep_temp)

prep_temp<-merge(prep_temp,prop_prep_temp,by=c("Var1"))

prep_temp$etiqueta<-paste(prettyNum(prep_temp$Freq.x,big.mark = ".",decimal.mark = ","),
              paste0("(",prettyNum(prep_temp$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

prep_temp<-prep_temp[,c(1,4)]

prep_temp$Var1<-as.character(prep_temp$Var1)

names(prep_temp)<-c("Variables", "Temprana")


# ----- Conductas sexules de riesgo

# ---- Hombre que practica sexo con hombres (sólo para los que no son usuarios del PrEP)

(hpsh_temp<-table(temprano$hombre_practica_sexo))

(prop_hpsh_temp<-round(prop.table(hpsh_temp),4))

hpsh_temp<-as.data.frame(hpsh_temp)
prop_hpsh_temp<-as.data.frame(prop_hpsh_temp)

hpsh_temp<-merge(hpsh_temp,prop_hpsh_temp,by=c("Var1"))

hpsh_temp$etiqueta<-paste(prettyNum(hpsh_temp$Freq.x,big.mark = ".",decimal.mark = ","),
              paste0("(",prettyNum(hpsh_temp$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

hpsh_temp<-hpsh_temp[,c(1,4)]

hpsh_temp$Var1<-as.character(hpsh_temp$Var1)

names(hpsh_temp)<-c("Variables", "Temprana")


# ---- Sexo transaccional

(st_temp<-table(temprano$participante_sexo_transaccional))

st_temp<-data.frame(Variables=c("Si","No"),
                    Temprana = c("0 (0)","0 (0)"))

#(prop_st_temp<-round(prop.table(st_temp),4))
#
#st_temp<-as.data.frame(st_temp)
#prop_st_temp<-as.data.frame(prop_st_temp)

#st_temp<-merge(st_temp,prop_st_temp,by=c("Var1"))
#
#st_temp$etiqueta<-paste(prettyNum(st_temp$Freq.x,big.mark = #".",decimal.mark = ","),
#              paste0("(",prettyNum(st_temp$Freq.y*100,big.mark = #".",decimal.mark = ","),")"))
#
#st_temp<-st_temp[,c(1,4)]
#
#st_temp$Var1<-as.character(st_temp$Var1)
#
#names(st_temp)<-c("Variables", "Temprana")


# ---- Múltiples parejas sexuales

(mps_temp<-table(temprano$participante_mult_parejas))

mps_temp<-data.frame(Variables=c("Si","No"),
                    Temprana = c("0 (0)","0 (0)"))

#(prop_mps<-round(prop.table(mps),4))
#
#mps<-as.data.frame(mps)
#prop_mps<-as.data.frame(prop_mps)
#
#mps<-merge(mps,prop_mps,by=c("Var1"))
#
#mps$etiqueta<-paste(prettyNum(mps$Freq.x,big.mark = ".",decimal.mark = #","),
#              paste0("(",prettyNum(mps$Freq.y*100,big.mark = #".",decimal.mark = ","),")"))
#
#mps<-mps[,c(1,4)]
#
#mps$Var1<-as.character(mps$Var1)
#
#names(mps)<-c("Variables", paste("Total n #=",prettyNum(length(datos_cohorte$participante_mult_parejas),big.mark = #".",decimal.mark = ",")))



# ---- Afiliación al sistema de salud

(afil_temp<-table(temprano$afiliciacion_seguridad_social))

(prop_afil_temp<-round(prop.table(afil_temp),4))

afil_temp<-as.data.frame(afil_temp)
prop_afil_temp<-as.data.frame(prop_afil_temp)

afil_temp<-merge(afil_temp,prop_afil_temp,by=c("Var1"))

afil_temp$etiqueta<-paste(prettyNum(afil_temp$Freq.x,big.mark = ".",decimal.mark = ","),
            paste0("(",prettyNum(afil_temp$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

afil_temp<-afil_temp[,c(1,4)]

afil_temp$Var1<-as.character(afil_temp$Var1)

names(afil_temp)<-c("Variables", "Temprana")



# ---- Escolaridad

(esco_temp<-table(temprano$escolaridad2))

(prop_esco_temp<-round(prop.table(esco_temp),4))

esco_temp<-as.data.frame(esco_temp)
prop_esco_temp<-as.data.frame(prop_esco_temp)

esco_temp<-merge(esco_temp,prop_esco_temp,by=c("Var1"))

esco_temp$etiqueta<-paste(prettyNum(esco_temp$Freq.x,big.mark = ".",decimal.mark = ","),
            paste0("(",prettyNum(esco_temp$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

esco_temp<-esco_temp[,c(1,4)]

esco_temp$Var1<-as.character(esco_temp$Var1)

names(esco_temp)<-c("Variables", "Temprana")


# ---- Número de personas con quienes vive

(convive_temp<-table(temprano$numero_personas_convive))

(prop_convive_temp<-round(prop.table(convive_temp),4))

convive_temp<-as.data.frame(convive_temp)
prop_convive_temp<-as.data.frame(prop_convive_temp)

convive_temp<-merge(convive_temp,prop_convive_temp,by=c("Var1"))

convive_temp$etiqueta<-paste(prettyNum(convive_temp$Freq.x,big.mark = ".",decimal.mark = ","),
            paste0("(",prettyNum(convive_temp$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

convive_temp<-convive_temp[,c(1,4)]

convive_temp$Var1<-as.character(convive_temp$Var1)

names(convive_temp)<-c("Variables", "Temprana")


```



```{r, include=FALSE}
# Tardia

# --- Edad

shapiro.test(tardio$edad)


edad_tard<-data.frame(Variables="Mediana (RIC)",
                 Total = paste(prettyNum(round(summary(tardio$edad)[3],2),big.mark = ".",decimal.mark = ","),
                               paste0("(",
                               prettyNum(round(summary(tardio$edad)[2],2),big.mark = ".",decimal.mark = ",")),
                               "-",
                        paste0(prettyNum(round(summary(tardio$edad)[5],2),big.mark = ".",decimal.mark = ","),
                                      ")")))

names(edad_tard)<-c("Variables", "Tardia")


# --- Sexo asignado al nacer

(sex_tard<-table(tardio$sexo))

(prop_sex_tard<-round(prop.table(sex_tard),4))

sex_tard<-as.data.frame(sex_tard)
prop_sex_tard<-as.data.frame(prop_sex_tard)

sex_tard<-merge(sex_tard,prop_sex_tard,by=c("Var1"))

sex_tard$etiqueta<-paste(prettyNum(sex_tard$Freq.x,big.mark = ".",decimal.mark = ","),
                    paste0("(",prettyNum(sex_tard$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

sex_tard<-sex_tard[,c(1,4)]

sex_tard$Var1<-as.character(sex_tard$Var1)

names(sex_tard)<-c("Variables", "Tardia")


# --- Identidad de genero

(genero2_tard<-table(tardio$genero2))

(prop_genero2_tard<-round(prop.table(genero2_tard),4))

genero2_tard<-as.data.frame(genero2_tard)
prop_genero2_tard<-as.data.frame(prop_genero2_tard)

genero2_tard<-merge(genero2_tard,prop_genero2_tard,by=c("Var1"))

genero2_tard$etiqueta<-paste(prettyNum(genero2_tard$Freq.x,big.mark = ".",decimal.mark = ","),
                paste0("(",prettyNum(genero2_tard$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

genero2_tard<-genero2_tard[,c(1,4)]

genero2_tard$Var1<-as.character(genero2_tard$Var1)

names(genero2_tard)<-c("Variables", "Tardia")


# --- Vive con VIH

(vih_tard<-table(tardio$vih))

(prop_vih_tard<-round(prop.table(vih_tard),4))

vih_tard<-as.data.frame(vih_tard)
prop_vih_tard<-as.data.frame(prop_vih_tard)

vih_tard<-merge(vih_tard,prop_vih_tard,by=c("Var1"))

vih_tard$etiqueta<-paste(prettyNum(vih_tard$Freq.x,big.mark = ".",decimal.mark = ","),
                paste0("(",prettyNum(vih_tard$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

vih_tard<-vih_tard[,c(1,4)]

vih_tard$Var1<-as.character(vih_tard$Var1)

names(vih_tard)<-c("Variables", "Tardia")



# --- Recuento CD4 (cél/µL)

shapiro.test(tardio$cd4)

cd4_tard<-data.frame(Variables="Mediana (RIC)",
                 Total = paste(prettyNum(round(summary(tardio$cd4)[3],2),big.mark = ".",decimal.mark = ","),
                               paste0("(",
                               prettyNum(round(summary(tardio$cd4)[2],2),big.mark = ".",decimal.mark = ",")),
                               "-",
                        paste0(prettyNum(round(summary(tardio$cd4)[5],2),big.mark = ".",decimal.mark = ","),
                                      ")")))

names(cd4_tard)<-c("Variables", "Tardia")



# --- Categorías de CD4

(cat_cd4_tard<-table(tardio$categorias_cd4))

(prop_cat_cd4_tard<-round(prop.table(cat_cd4_tard),4))

cat_cd4_tard<-as.data.frame(cat_cd4_tard)
prop_cat_cd4_tard<-as.data.frame(prop_cat_cd4_tard)

cat_cd4_tard<-merge(cat_cd4_tard,prop_cat_cd4_tard,by=c("Var1"))

cat_cd4_tard$etiqueta<-paste(prettyNum(cat_cd4_tard$Freq.x,big.mark = ".",decimal.mark = ","),
              paste0("(",prettyNum(cat_cd4_tard$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

cat_cd4_tard<-cat_cd4_tard[,c(1,4)]

cat_cd4_tard$Var1<-as.character(cat_cd4_tard$Var1)

names(cat_cd4_tard)<-c("Variables", "Tardia")



# --- Prep

(prep_tard<-table(tardio$prep))

(prop_prep_tard<-round(prop.table(prep_tard),4))

prep_tard<-as.data.frame(prep_tard)
prop_prep_tard<-as.data.frame(prop_prep_tard)

prep_tard<-merge(prep_tard,prop_prep_tard,by=c("Var1"))

prep_tard$etiqueta<-paste(prettyNum(prep_tard$Freq.x,big.mark = ".",decimal.mark = ","),
              paste0("(",prettyNum(prep_tard$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

prep_tard<-prep_tard[,c(1,4)]

prep_tard$Var1<-as.character(prep_tard$Var1)

names(prep_tard)<-c("Variables", "Tardia")


# ----- Conductas sexules de riesgo

# ---- Hombre que practica sexo con hombres (sólo para los que no son usuarios del PrEP)

(hpsh_tard<-table(tardio$hombre_practica_sexo))

(prop_hpsh_tard<-round(prop.table(hpsh_tard),4))

hpsh_tard<-as.data.frame(hpsh_tard)
prop_hpsh_tard<-as.data.frame(prop_hpsh_tard)

hpsh_tard<-merge(hpsh_tard,prop_hpsh_tard,by=c("Var1"))

hpsh_tard$etiqueta<-paste(prettyNum(hpsh_tard$Freq.x,big.mark = ".",decimal.mark = ","),
              paste0("(",prettyNum(hpsh_tard$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

hpsh_tard<-hpsh_tard[,c(1,4)]

hpsh_tard$Var1<-as.character(hpsh_tard$Var1)

names(hpsh_tard)<-c("Variables", "Tardia")


# ---- Sexo transaccional

(st_tard<-table(tardio$participante_sexo_transaccional))

(prop_st_tard<-round(prop.table(st_tard),4))

st_tard<-as.data.frame(st_tard)
prop_st_tard<-as.data.frame(prop_st_tard)

st_tard<-merge(st_tard,prop_st_tard,by=c("Var1"))

st_tard$etiqueta<-paste(prettyNum(st_tard$Freq.x,big.mark = ".",decimal.mark = ","),
              paste0("(",prettyNum(st_tard$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

st_tard<-st_tard[,c(1,4)]

st_tard$Var1<-as.character(st_tard$Var1)

names(st_tard)<-c("Variables", "Tardia")


# ---- Múltiples parejas sexuales

(mps_tard<-table(tardio$participante_mult_parejas))


(prop_mps_tard<-round(prop.table(mps_tard),4))

mps_tard<-as.data.frame(mps_tard)
prop_mps_tard<-as.data.frame(prop_mps_tard)

mps_tard<-merge(mps_tard,prop_mps_tard,by=c("Var1"))

mps_tard$etiqueta<-paste(prettyNum(mps_tard$Freq.x,big.mark = ".",decimal.mark = ","),
              paste0("(",prettyNum(mps_tard$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

mps_tard<-mps_tard[,c(1,4)]

mps_tard$Var1<-as.character(mps_tard$Var1)

names(mps_tard)<-c("Variables", "Tardia")



# ---- Afiliación al sistema de salud

(afil_tard<-table(tardio$afiliciacion_seguridad_social))

(prop_afil_tard<-round(prop.table(afil_tard),4))

afil_tard<-as.data.frame(afil_tard)
prop_afil_tard<-as.data.frame(prop_afil_tard)

afil_tard<-merge(afil_tard,prop_afil_tard,by=c("Var1"))

afil_tard$etiqueta<-paste(prettyNum(afil_tard$Freq.x,big.mark = ".",decimal.mark = ","),
            paste0("(",prettyNum(afil_tard$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

afil_tard<-afil_tard[,c(1,4)]

afil_tard$Var1<-as.character(afil_tard$Var1)

names(afil_tard)<-c("Variables", "Tardia")



# ---- Escolaridad

(esco_tard<-table(tardio$escolaridad2))

(prop_esco_tard<-round(prop.table(esco_tard),4))

esco_tard<-as.data.frame(esco_tard)
prop_esco_tard<-as.data.frame(prop_esco_tard)

esco_tard<-merge(esco_tard,prop_esco_tard,by=c("Var1"))

esco_tard$etiqueta<-paste(prettyNum(esco_tard$Freq.x,big.mark = ".",decimal.mark = ","),
            paste0("(",prettyNum(esco_tard$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

esco_tard<-esco_tard[,c(1,4)]

esco_tard$Var1<-as.character(esco_tard$Var1)

names(esco_tard)<-c("Variables", "Tardia")


# ---- Número de personas con quienes vive

(convive_tard<-table(tardio$numero_personas_convive))

(prop_convive_tard<-round(prop.table(convive_tard),4))

convive_tard<-as.data.frame(convive_tard)
prop_convive_tard<-as.data.frame(prop_convive_tard)

convive_tard<-merge(convive_tard,prop_convive_tard,by=c("Var1"))

convive_tard$etiqueta<-paste(prettyNum(convive_tard$Freq.x,big.mark = ".",decimal.mark = ","),
            paste0("(",prettyNum(convive_tard$Freq.y*100,big.mark = ".",decimal.mark = ","),")"))

convive_tard<-convive_tard[,c(1,4)]

convive_tard$Var1<-as.character(convive_tard$Var1)

names(convive_tard)<-c("Variables", "Tardia")


```



```{r, include=FALSE}
#### Adjuntar las bases

# --- Edad
edad_0<-merge(edad_temp,edad_tard,all = T)
#edad<-merge(edad_0,edad,all = T)

# --- Sexo
sex_0<-merge(sex_temp,sex_tard,all = T)
#sex<-merge(sex_0,sex,all = T)
sex_0<-sex_0[order(match(sex_0$Variables, c("Masculino","Femenino"))),]

# ---- Identidad de Genero
genero_0<-merge(genero2_temp,genero2_tard,all = T)
#genero<-merge(genero_0,genero2,all = T)
genero_0<-genero_0[order(match(genero_0$Variables, c("Hombre cisgenero",
                                               "Mujer cisgenero",
                                               "Mujer transgenero",
                                                  "Indefinido"))),]

# ---- Vive con VIH
vih_0<-merge(vih_temp,vih_tard,all = T)
#vih<-merge(vih_0,vih,all = T)
vih_0<-vih_0[order(match(vih_0$Variables, c("Si",
                                         "No"))),]


# ---- Recuento CD4 (cél/µL)

cd4_0<-merge(cd4_temp,cd4_tard,all = T)
#cd4<-merge(cd4_0,cd4,all = T)


# ---- Categoria CD4 (cél/µL)

cat_cd4_0<-merge(cat_cd4_temp,cat_cd4_tard,all = T)
#cat_cd4<-merge(cat_cd4_0,cat_cd4,all = T)

# ---- Usuario de PrEP

prep_0<-merge(prep_temp,prep_tard,all = T)
#prep<-merge(prep_0,prep,all = T)
prep_0<-prep_0[order(match(prep_0$Variables, c("Si",
                                         "No"))),]

# ----- Conductas sexules de riesgo

# ---- Hombre que practica sexo con hombres (sólo para los que no son usuarios del PrEP)

hpsh_0<-merge(hpsh_temp,hpsh_tard,all = T)
#hpsh<-merge(hpsh_0,hpsh,all = T)
hpsh_0<-hpsh_0[order(match(hpsh_0$Variables, c("Si",
                                         "No"))),]

# ---- Sexo transaccional

st_0<-merge(st_temp,st_tard,all = T)
#st<-merge(st_0,st,all = T)
st_0<-st_0[order(match(st_0$Variables, c("Si",
                                         "No"))),]

# ---- Múltiples parejas sexuales

mps_0<-merge(mps_temp,mps_tard,all = T)
#mps<-merge(mps_0,mps,all = T)
mps_0<-mps_0[order(match(mps_0$Variables, c("Si",
                                         "No"))),]

# ---- Afiliación al sistema de salud

afil_0<-merge(afil_temp,afil_tard,all = T)
#afil<-merge(afil_0,afil,all = T)
afil_0<-afil_0[order(match(afil_0$Variables, c("Contributivo",
                                         "Subsidiado",
                                         "Especial",
                                         "Ninguno",
                                         "Otro"))),]


# ---- Escolaridad

esco_0<-merge(esco_temp,esco_tard,all = T)
#esco<-merge(esco_0,esco,all = T)
esco_0<-esco_0[order(match(esco_0$Variables, c("Baja",
                                         "Media",
                                         "Alta"))),]

# ---- numero convive

convive_0<-merge(convive_temp,convive_tard,all = T)
#convive<-merge(convive_0,convive,all = T)

```

```{r, include=FALSE}
tabla1<-rbind(c("Edad en años","",""),
              edad_0,
              c("","",""),
              c("Sexo","n (%)","n (%)"),
              sex_0,
              c("","",""),
              c("Identidad de género","",""),
              genero_0,
              c("","",""),
              c("Vive con VIH","",""),
              vih_0,
              c("","",""),
              c("Recuento CD4 (cél/µL)","",""),
              cd4_0,
              c("","",""),
              c("Categoria CD4 (cél/µL)","",""),
              cat_cd4_0,
              c("","",""),
              c("Usuario de PrEP","",""),
              prep_0,
              c("","",""),
              c("Conductas sexules de riesgo","",""),
              c("Hombre que practica sexo con hombres","",""),
              hpsh_0,
              c("","",""),
               c("Sexo transaccional","",""),
              st_0,
              c("","",""),
               c("Múltiples parejas sexuales","",""),
              mps_0,
              c("","",""),
               c("Afiliación al sistema de salud","",""),
              afil_0,
              c("","",""),
               c("Escolaridad","",""),
              esco_0,
              c("","",""),
               c("Número de personas con quien convive","",""),
              convive_0)
```



```{r, include=FALSE}
##

# --- Edad

tabla1$estadistico[tabla1$Variables == "Edad en años"] <- prettyNum(round(wilcox.test(edad ~ asignacion,data=datos_eca,
                                   alternative = "two.sided", 
                                   mu = 0)$statistic,2),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Edad en años"]<-prettyNum(round(wilcox.test(edad ~ asignacion, 
                                   data=datos_eca,
                                   alternative = "two.sided", 
                                   mu = 0)$p.value,3),big.mark = ".",decimal.mark = ",")



# --- Sexo

tabla1$estadistico[tabla1$Variables == "Masculino"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$sexo,
                                                                                           datos_eca$asignacion)))$statistic,3),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Masculino"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$sexo,
                                                                                           datos_eca$asignacion)))$p.value,3),big.mark = ".",decimal.mark = ",")



# --- Género

tabla1$estadistico[tabla1$Variables == "Hombre cisgenero"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$genero2,datos_eca$asignacion)))$statistic,3),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Hombre cisgenero"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$genero2,datos_eca$asignacion)))$p.value,3),big.mark = ".",decimal.mark = ",")



# --- Vive con VIH

tabla1$estadistico[tabla1$Variables == "Vive con VIH"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$vih,datos_eca$asignacion)))$statistic,3),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Vive con VIH"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$vih,datos_eca$asignacion)))$p.value,3),big.mark = ".",decimal.mark = ",")




# --- 	Recuento CD4 (cél/µL)

tabla1$estadistico[tabla1$Variables == "Recuento CD4 (cél/µL)"]<-prettyNum(round(wilcox.test(cd4 ~ asignacion, 
                                   data=datos_eca,
                                   alternative = "two.sided", 
                                   mu = 0)$statistic,2),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Recuento CD4 (cél/µL)"]<-prettyNum(round(wilcox.test(cd4 ~ asignacion, 
                                   data=datos_eca,
                                   alternative = "two.sided", 
                                   mu = 0)$p.value,3),big.mark = ".",decimal.mark = ",")


# --- Categorías CD4

tabla1$estadistico[tabla1$Variables == "Categoria CD4 (cél/µL)"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$categorias_cd4,datos_eca$asignacion)))$statistic,3),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Categoria CD4 (cél/µL)"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$categorias_cd4,datos_eca$asignacion)))$p.value,3),big.mark = ".",decimal.mark = ",")


# --- Prep

tabla1$estadistico[tabla1$Variables == "Usuario de PrEP"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$prep,datos_eca$asignacion)))$statistic,3),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Usuario de PrEP"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$prep,datos_eca$asignacion)))$p.value,3),big.mark = ".",decimal.mark = ",")



# --- Hombre que parctica sexo xon otros hombres

tabla1$estadistico[tabla1$Variables == "Hombre que practica sexo con hombres"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$hombre_practica_sexo,datos_eca$asignacion)))$statistic,3),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Hombre que practica sexo con hombres"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$hombre_practica_sexo,datos_eca$asignacion)))$p.value,3),big.mark = ".",decimal.mark = ",")


# --- Sexo transaccional

tabla1$estadistico[tabla1$Variables == "Sexo transaccional"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$participante_sexo_transaccional,datos_eca$asignacion)))$statistic,3),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Sexo transaccional"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$participante_sexo_transaccional,datos_eca$asignacion)))$p.value,3),big.mark = ".",decimal.mark = ",")


# --- Múltiples parejas sexuales

tabla1$estadistico[tabla1$Variables == "Múltiples parejas sexuales"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$participante_mult_parejas,datos_eca$asignacion)))$statistic,3),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Múltiples parejas sexuales"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$participante_mult_parejas,datos_eca$asignacion)))$p.value,3),big.mark = ".",decimal.mark = ",")



# ---	Afiliación al sistema de salud

tabla1$estadistico[tabla1$Variables == "Afiliación al sistema de salud"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$afiliciacion_seguridad_social,datos_eca$asignacion)))$statistic,3),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Afiliación al sistema de salud"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$afiliciacion_seguridad_social,datos_eca$asignacion)))$p.value,3),big.mark = ".",decimal.mark = ",")


# ---	Escolaridad

tabla1$estadistico[tabla1$Variables == "Escolaridad"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$escolaridad2,datos_eca$asignacion)))$statistic,3),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Escolaridad"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$escolaridad2,datos_eca$asignacion)))$p.value,3),big.mark = ".",decimal.mark = ",")


# ---- Número de personas con quienes vive

tabla1$estadistico[tabla1$Variables == "Número de personas con quien convive"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$numero_personas_convive,datos_eca$asignacion)))$statistic,3),big.mark = ".",decimal.mark = ",")

tabla1$p_val[tabla1$Variables == "Número de personas con quien convive"]<-prettyNum(round(chisq.test(as.matrix(table(datos_eca$numero_personas_convive,datos_eca$asignacion)))$p.value,3),big.mark = ".",decimal.mark = ",")


############ -------------- Cambiar los NA por vacíos

tabla1$p_val[is.na(tabla1$p_val)]<-""

tabla1$estadistico[is.na(tabla1$estadistico)]<-""


tabla1$Temprana[is.na(tabla1$Temprana)]<-"0 (0)"
tabla1$Tardia[is.na(tabla1$Tardia)]<-"0 (0)"

############ -------------- Cambiar los valores de p de 1 o 0

tabla1$p_val[tabla1$p_val == 1]<-"> 0,999"
tabla1$p_val[tabla1$p_val == 0]<-"< 0,001"

############ -------------- cambiar nombres de las variables

names(tabla1)[names(tabla1) %in% c("Temprana",
                                   "Tardia",
                                   "p_val")]<-c(paste("Temprana n =",length(temprano$record_id)),
                             paste("Tardía n =",length(tardio$record_id)),"p-value")

```


```{r,echo=FALSE}
tabla1
```




